version: "3.9"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ../data/redis:/data
  db:
    image: mysql
    container_name: db
    volumes:
      - ../data/db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
  web:
    build: .
    container_name: web
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_NAME=django
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    depends_on:
      - db
      - redis
