# Generated by Django 4.1.7 on 2023-03-25 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date_time', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_first_user', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fr_second_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend_request',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_first_user', to=settings.AUTH_USER_MODEL)),
                ('friend_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_request', to='chat.friendrequest')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_second_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends',
                'unique_together': {('first_user', 'second_user')},
            },
        ),
        migrations.CreateModel(
            name='ChatMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_members',
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
